### ISSUE TITLE
Rename Repo

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/sdk-archivist-nodejs#10]
I think this repo should be called api-archivist-graphql and the sdk-archivist-nodejs repo should have all the archivist specific non-core, non-api code

**Comment by ryanxyo** [comment]
@justinffortier Could you please make a repo named `api-archivist-graphql`

**Comment by justinffortier** [comment]
➤ Justin Fortier commented:

@Ryan Pillsbury here is the repo: https://github.com/XYOracleNetwork/api-archivist-graphql
