### ISSUE TITLE
About Call in GraphQL

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/sdk-archivist-nodejs#11]
Please add an about branch in the graphQL

archivist (root)
 about

type About {
 name: String,
 version: String,
 url: String,
 address: String
}

**Comment by ryanxyo** [comment]
@arietrouw @justinffortier 

I am confused about the fields inside the `About` object. In particular:

`name` - What is it? Where does it come from? What value does it provide?

`version` - We do not really have a fully-baked concept of versioning yet. What were you envisioning for  this?

`url` - Is this the publicly addressable ip of the archivist? Such as, what would come from a google query [Whats my ip](https://www.google.com/search?q=whats+my+ip&rlz=1C5CHFA_enUS808US808&oq=whats+my+ip&aqs=chrome..69i57j0l5.1866j1j7&sourceid=chrome&ie=UTF-8)

`address` - What is the difference between url and address?
